### ISSUE TITLE
cytoscape no working

### ISSUE THREAD

**Issue by jfertaj** [idekerlab/heat-diffusion#1]
Hi I am trying to run Diffussion on cytoscape 3.6.0 but I get the error about not able to parse diffusion results, I have followed the protocol in the Plos Comp Biol paper, any ideas what is going on?

Thanks

**Comment by coleslaw481** [comment]
Sorry about the delay in reply. Does it work now if you use Cytoscape 3.8.2?

**Comment by coleslaw481** [comment]
Assuming this was a transient problem. Please re-open if issue is still encountered with Cytoscape 3.8.2+
